jdk:
  - oraclejdk8
  - openjdk11

language: scala

scala:
  - 2.13.0
  - 2.12.8

sudo: required

services:
  - docker

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport coverageAggregate coveralls

jobs:
  include:
    - stage: integration
      scala: 2.13.0
      env: AKKA_TEST_TIMEFACTOR=1.5 AKKA_TEST_LOGLEVEL=OFF
      before_install:
        - docker pull eventstore/eventstore:release-5.0.1
        - docker run -d --rm --name eventstore-node -p 2113:2113 -p 1113:1113 -e EVENTSTORE_MEM_DB=True -e EVENTSTORE_STATS_PERIOD_SEC=1200 eventstore/eventstore:release-5.0.1
      script:
        - sbt test:compile
        - travis_retry sbt it:test

cache:
  # These directories are cached to S3 at the end of the build
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
