version: '3.8'
services:

  esdb01:
    image: eventstore/eventstore:21.10.0-bionic
    environment:
      - EVENTSTORE_MEM_DB=True
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=True
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_DISCOVER_VIA_DNS=False
      - EVENTSTORE_INSECURE=True
      - EVENTSTORE_GOSSIP_SEED=172.24.0.3:2113,172.24.0.4:2113
      - EVENTSTORE_CLUSTER_SIZE=3
      - EVENTSTORE_INT_IP=172.24.0.2
    ports:
      - 2114:2113
      - 1114:1113
    networks:
      esdb_cluster_network:
        ipv4_address: 172.24.0.2
    restart: unless-stopped

  esdb02:
    image: eventstore/eventstore:21.10.0-bionic
    environment:
      - EVENTSTORE_MEM_DB=True
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=True
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_DISCOVER_VIA_DNS=False
      - EVENTSTORE_INSECURE=True
      - EVENTSTORE_GOSSIP_SEED=172.24.0.2:2113,172.24.0.4:2113
      - EVENTSTORE_CLUSTER_SIZE=3
      - EVENTSTORE_INT_IP=172.24.0.3
    ports:
      - 2115:2113
      - 1115:1113
    networks:
      esdb_cluster_network:
        ipv4_address: 172.24.0.3
    restart: unless-stopped

  esdb03:
    image: eventstore/eventstore:21.10.0-bionic
    environment:
      - EVENTSTORE_MEM_DB=True
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=True
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_DISCOVER_VIA_DNS=False
      - EVENTSTORE_INSECURE=True
      - EVENTSTORE_GOSSIP_SEED=172.24.0.2:2113,172.24.0.3:2113
      - EVENTSTORE_CLUSTER_SIZE=3      
      - EVENTSTORE_INT_IP=172.24.0.4
    ports:
      - 2116:2113
      - 1116:1113
    networks:
      esdb_cluster_network:
        ipv4_address: 172.24.0.4
    restart: unless-stopped

networks:
  esdb_cluster_network:
    name: esdb-cluster-net
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16
